hazard_codes = {
    "EN0013" : "Wildfire",
    "nat-hyd-flo-flo" : "Flood",
    "nat-met-sto-sto" : "Storm",
    "FL" : "Flood",
    "MH0600" : "Flood",
    "VW" : "Violent wind",
    "MH0301" : "Wind",
    "nat-cli-wil-for" : "Forest fire",
    "nat-met-sto-hai" : "Hail",
    "mix-mix-mix-mix" : "Complex Emergency",
    "nat-geo-mmd-lan" : "Landslide",
    "WF" : "Wildfire",
    "LS" : "Landslide",
    "GH0300" : "Landslide",
    "nat-cli-wil-wil" : "Wildfire",
    "nat-hyd-mmw-lan" : "Landslide",
    "ST" : "Hail",
    "MH0404" : "Hail",
    "nat-bio-epi-dis" : "Epidemic",
    "EN0205" : "Wildfire",
    "MH0012" : "Flood",
    "EP" : "Epidemic",
    "DR" : "Drought",
    "nat-cli-dro-dro" : "Drought",
    "nat-geo-ear-gro" : "Earthquake",
    "MH0035" : "Drought",
    "MH0103" : "Thunderstorm",
    "nat-geo-env-soi" : "Soil Erosion",
    "MH0401" : "Drought",
    "GH0101" : "Earthquake",
    "EQ" : "Earthquake",
    "EN0019" : "Soil Erosion",
    "GH0001" : "Earthquake",
    "CE" : "Complex Emergency",
    "OT" : "Other",
    "nat-geo-vol-vol" : "Volcanic Activity",
    "nat-hyd-flo-fla" : "Flash Flood",
    "FF" : "Flash Flood",
    "VO" : "Volcanic Activity",
    "GH009" : "Volcanic Activity",
    "GH0403" : "Soil Erosion",
    "GH0016" : "Volcanic Activity",
    "GH0015" : "Volcanic Activity",
    "GH0014" : "Volcanic Activity",
    "GH0013" : "Volcanic Activity",
    "MH0057" : "Tropical Cyclone",
    "MH0032" : "Tropical Cyclone",
    "nat-met-tro-tro" : "Tropical Cyclone",
    "MH0031" : "Tropical Cyclone",
    "MH0006" : "Flash Flood",
    "MH0030" : "Tropical Cyclone",
    "MH0027" : "Storm",
    "GH0004" : "Earthquake",
    "TC" : "Tropical Cyclone",
    "nat-met-sto-tro" : "Tropical Cyclone",
}